### ISSUE TITLE
I can't get swipe to delete to work :O

### ISSUE THREAD

**Issue by kitlangton** [RxSwiftCommunity/RxRealmDataSources#4]
Hey! Firstly, thanks so much for this. Everything is going swimmingly besides this.

The only problem is that I am unable to get swipe to delete to work.

```swift
        tableView.delegate = nil
        tableView.dataSource = nil
        
        let dataSource = RxTableViewRealmDataSource<RealmRecording>(cellIdentifier: "RecordingCell", cellType: RecordingCell.self) {cell, ip, recording in
            cell.configure(forRecording: recording)
        }
        
        Observable.changesetFrom(song.recordings)
            .debug()
            .bindTo(tableView.rx.realmChanges(dataSource))
            .addDisposableTo(self.disposeBag)
        
        // This works perfectly.
        tableView.rx.itemSelected
            .subscribe(onNext: { ip in
                let recording = self.song.recordings[ip.row]
                self.delegate.didSelect(recording: recording)
            })
            .addDisposableTo(disposeBag)
        
        // But this does not. Nothing happens when I swipe on my rows.
        tableView.rx.itemDeleted
            .subscribe(onNext: { ip in
                print(ip, "DELETED")
            })
            .addDisposableTo(disposeBag)
```

Am I forgetting something? :O

Thank you!

**Comment by kitlangton** [comment]
Ah, I believe it's because the iOS code doesn't implement a dataSource proxy.

Is there a reason why only the macOS version implements this:

```swift
public override func responds(to aSelector: Selector!) -> Bool {
            if RxTableViewRealmDataSource.instancesRespond(to: aSelector) {
                return true
            } else if let delegate = delegate {
                return delegate.responds(to: aSelector)
            } else if let dataSource = dataSource {
                return dataSource.responds(to: aSelector)
            } else {
                return false
            }
        }
```

**Comment by icanzilb** [comment]
Truth is - I'm still trying to figure out what's the right thing to do ... 

The data source delegate for UITableView is very simple, so it's easy for RxTableViewRealmDataSource to overwrite all methods. 

In contrast the NSTableView data source protocol has much more methods you might want to implement and customize. 

So ... what the lib currently does is to allow you to set the `delegate` property of the `UITableView` while using RxTableViewRealmDataSource for data source.

With NSTableView is more complicated because tbh the methods in the data source and delegate are quite mixed up, some have to do with appearance, some data, it's all intermixed. So I ended up having to allow RxTableViewRealmDataSource serve as both data source and delegate.

I don't mind adopting delegate methods for UITableVIew in RxTableViewRealmDataSource. The only thing that bothers me (and I don't have time to attend to) is the performance penalty there might be for proxying the data source and delegate methods through that class. 

E.g. my concern is what is the difference performance-wise between:
 * setting delegate directly on the table view (which you can do)
 * setting delegate on RxTableViewRealmDataSource, which will then proxy the method to your own object.

**Comment by LiuSky** [comment]
Is there any new progress? @icanzilb

**Comment by icanzilb** [comment]
hi @LiuSky this issue is closed, if you experience a bug or want to request a feature open a new issue

**Comment by LiuSky** [comment]
Well, thanks @icanzilb , I have a version of the fork, and made a change.
